### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by mtzro2003** [gytisgreitai/openhab-google-home#1]
Hi!
I'd like to test your implementation which is faaaaar more flexible than the "standard" openhab one :))
However, got some questions about the docker part...
Is there some way to use it without Let's Encrypt?
I already have cert for my domain and I could mount the path to them in the container...
Another one... Would the connection between Google and my domain work with another port than 443? HTTPS - yes, but another port... something like https://your-domain-name:4443/smarthome?

**Comment by gytisgreitai** [comment]
So you need a docker image, but without let's encrypt? I could create an env variable which just turns off let's encrypt functionality and then you could mount your cert directory under`/usr/share/nginx/certificates/` which should contain files called `fullchain.pem` and `privkey.pem`

Another option would be to have a docker container that just has the app itself without nginx. 

I could also publish app as a single .js file (which is already used in docker) so if you have node >=8 you could just run that.

Regarding the ports, I don't see why not. Google does seem to accept https url with a port, so afaik all should be good.

**Comment by mtzro2003** [comment]
Well, all of the options you described would be fine with me, but I believe you should choose one that will suit more users.
As I said, I think your GA approach provides much more flexibility, so a whole bunch of openhab users might want to it.
Some of them might be in my position... :smile: 
Whatever you choose, I'm sure it'll be alright!

**Comment by gytisgreitai** [comment]
Ok, so I've updated the docker images and [docs](https://github.com/gytisgreitai/openhab-google-home/blob/master/docs/standalone.md)

Now you can run with let's encrypt disabled, same image just pass in `-e DISABLE_LETS_ENCRYPT=true` and mount your certs under `/usr/share/nginx/certificates/`

Or run just the app without nginx, then use this image `gytisgreitai/openhab-ga-unofficial-demo:app-only`

**Comment by mtzro2003** [comment]
Excellent!
I'll close this for now and open a new ticket with my findings.
Thanks!
