### ISSUE TITLE
Docker container works on x86 ubuntu machine but not on Pi (openhabian)

### ISSUE THREAD

**Issue by djmillsuk** [gytisgreitai/openhab-google-home#4]
I have my openhabian running on a Pi4 (B) and the docker instance running on my ubuntu server machine. The reason for this is that the docker container will not work on the Pi, do you have any idea why that is?

the logs reads....

```
[11:34:30] openhabian@openhab:/etc/openhab2/items$ sudo docker logs <redacted>
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by gytisgreitai** [comment]
Ok, it seems that you need to build docker image specifically for ARM. I've pushed one with armv7 support, can you see and check if this one works `gytisgreitai/openhab-ga-unofficial-demo:experimental` ?

**Comment by djmillsuk** [comment]
sounds good, ill try it as soon as im home, thanks.

**Comment by djmillsuk** [comment]
brilliant, works perfectly, you're smashing it!

**Comment by gytisgreitai** [comment]
Ok, so I've pushed armv7 with the :latest tag, you can revert back to `gytisgreitai/openhab-ga-unofficial-demo:latest` should be ok. Thanks for reporting.
