### ISSUE TITLE
REMOTECONTROL: add action.devices.commands.mediaStop

### ISSUE THREAD

**Issue by mtzro2003** [gytisgreitai/openhab-google-home#8]
I'd like to request to add `action.devices.commands.mediaStop` to `action.devices.traits.MediaState`.
Even if openHAB `player` item does not include a `stop`  command type, the problem could be circumvented using a `string` item as `action.devices.types.REMOTECONTROL` and a simple rule.

**Comment by gytisgreitai** [comment]
pull latest
