### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by smar000** [gytisgreitai/openhab-google-home#9]
Any chance you could upload your Dockerfile for the `gytisgreitai/openhab-ga-unofficial-demo:app-only`, so that we can build our own containers and stay up to date.

Many thanks

**Comment by gytisgreitai** [comment]
All docker files are on git hub. app only is this one https://github.com/gytisgreitai/openhab-google-home/blob/master/remote/docker/app/Dockerfile

**Comment by smar000** [comment]
Thanks and just saw it!

**Comment by smar000** [comment]
The docker build is failing on:

`COPY dist .`

I'm not seeing `dist` anywhere. Is this something that has to be built locally?

**Comment by gytisgreitai** [comment]
Build is handled via Makefile https://github.com/gytisgreitai/openhab-google-home/blob/master/remote/Makefile

so basically you have to:
```
yarn workspaces run tsc -b
cd remote 
docker buildx build --platform linux/arm/v7,linux/amd64,linux/arm64 -t your-tag-name   -f docker/app/Dockerfile .
```

But what are you trying to achieve? master is  currently a bit of a WIP because of local execution, it might not even work :)

**Comment by smar000** [comment]
Thanks and I realised what was happening when I saw the Makefile.

Actually I was just looking to update to see where you were with the local execution. No urgency or issues with my existing setup - it is working very well in fact (for which thank you again!).

**Comment by gytisgreitai** [comment]
Well I could make a docker image with local execution and updated the docs if you want to test, but afaik it is not worth the effort. Google side is not polished, 50% of the time it just says "sorry XXX is not available" and afaik  from my experience it is even slower than cloud execution, sometimes it just hangs - my mini flashes the lights and nothing happens.

**Comment by smar000** [comment]
Thanks but in that case probably not worth your spending time until Google sort their side out. I was only interested from an improved performance perspective as compared to the existing cloud execution times.

**Comment by gytisgreitai** [comment]
What hardware do you have? Perhaps the new Home Nest Mini ?

**Comment by smar000** [comment]
No, just a bunch of the original Google Home Minis.
